In [8]:
import pandas as pd

In [9]:
!pip install xlrd

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [10]:
url = r'C:\Users\julia\OneDrive\Documentos\Ironhack\GSAF5.csv'

shark_attack = pd.read_csv(
    url,
    encoding="latin1",
    sep=None,
    engine="python"
)

In [11]:
#show columns

shark_attack.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [12]:
#drop the columns we don't need

shark_attack = shark_attack.drop(
    columns=[
        'Name', 'Source', 'pdf', 'href formula', 'href',
        'Case Number', 'Case Number.1', 'original order',
        'Unnamed: 21', 'Unnamed: 22'
    ]
)

In [13]:
#drop the rows older than 1975 (left 50 years)
shark_attack = shark_attack[shark_attack['Year'] > 1975]

In [14]:
shark_attack

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Fatal Y/N,Time,Species
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,1015hrs,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,1030hrs,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,1730hrs,Unknown
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,0945hrs,Unknown
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,1640hrs,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,12/jan/76,1976.0,Unprovoked,AUSTRALIA,Queensland,Harvey Bay,NaN,F,NaN,Survived,N,NaN,NaN
3996,11/jan/76,1976.0,Provoked,SOUTH AFRICA,Western Cape Province,Kalk Bay,Fishing for snoek & yellowtail,NaN,NaN,"Hooked shark leapt onboard & into fish well, w...",N,07h30,"White shark, 3 m [10']"
3997,08/jan/76,1976.0,Unprovoked,USA,Florida,"Off Fort Pierce, St Lucie County",Spearfishing / scuba diving,M,25,Puncture wounds to head & neck,N,NaN,6' shark
3998,02/jan/76,1976.0,Unprovoked,NEW ZEALAND,North Island,"Te Kaha, East coast",Spearfishing,M,NaN,FATAL,Y,13h00,Bronze whaler shark
3999,1976,1976.0,Unprovoked,USA,Hawaii,"Off Lahaina, Maui",Scuba diving,M,NaN,"FATAL, lost consciousness at depth of 180'. La...",Y,NaN,NaN

In [15]:
# Select only the columns I want to clean
columns_to_clean = ["Country", "State", "Location", "Activity"]

shark_clean = shark_attack[columns_to_clean].copy()

In [16]:
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    211
dtype: int64

In [17]:
# Remove extra spaces
for column in columns_to_clean:
    shark_clean[column] = shark_clean[column].str.strip()
display(shark_clean.head())

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,USA,Hawaii,Honolulu,Surfing

In [18]:
# Replace empty strings with NaN
shark_clean = shark_clean.replace(r"^\s*$", pd.NA, regex=True)

In [19]:
# Standardize capitalization
shark_clean["Country"] = shark_clean["Country"].str.title()
shark_clean["State"] = shark_clean["State"].str.title()
shark_clean["Location"] = shark_clean["Location"].str.title()

In [20]:
# For Activity, remove extra spaces
shark_clean["Activity"] = shark_clean["Activity"].str.strip()

In [21]:
# Check missing values again
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    212
dtype: int64

In [22]:
# Check cleaned data
display(shark_clean.head(20))

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off The Coast Of Perce Le Bilbo Dive Site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,Usa,Hawaii,Honolulu,Surfing
5,Usa,Florida,New Smyrna Beach,Surfing
6,Usa,Florida,30 Miles Off Pensacola,Spearfishing
7,Usa,Massachusetts,Norton Point Edgartown Marthas Vinyard,Swimming
8,Usa,Hawaii,"Ala Moana Beach Park, Oahu",Surfing
9,Usa,Florida,Boca Grande (Island In The Keys),Wading on a sandbar
10,Reunion Island,Saint-Gilles-Les-Baines,Outer Reef Roches Noires,Spearfishiong
11,Ireland,Waterford,Ardemore County,Fishing
12,Usa,Maine,Scarborough Beach Park,Operation of Rescue Torpedo
13,Usa,South Carolina,Murrells Inlet Garden City,Swimming
14,Usa,Florida,Daytona Beach Shores Volusia County,Swimming
15,Bahamas,Not Stated,Nort Stated,Snorkeling
16,Fiji,Not Stated,Not Stated,Spearfishing
17,Australia,Queensland,Bundaberg,Hydrofoiling
18,Australia,Tasmania,Coral Point Bruny Island,Spearfishing
19,Usa,New York,Jones Beach State Park Long Island,Swimming

In [23]:
# Select only the columns I want to clean (y = Yurii)
columns_to_clean_y = ['Sex', 'Age', 'Injury']

shark_clean_y = shark_attack[columns_to_clean_y].copy()

shark_clean_y

      Sex   Age                                             Injury
0       M    63                                 Body not recovered
1       M     ?               Injuries to chest shoulder and back
2       F    37                    Serious injuries to right ankle
3       M  50's                                Foot lost in attack
4      M     24                          Scrapes on inside of legs
...   ...   ...                                                ...
3995    F   NaN                                           Survived
3996  NaN   NaN  Hooked shark leapt onboard & into fish well, w...
3997    M    25                     Puncture wounds to head & neck
3998    M   NaN                                              FATAL
3999    M   NaN  FATAL, lost consciousness at depth of 180'. La...

[3998 rows x 3 columns]

In [24]:
# cleaning "Sex"

shark_clean_y["Sex"] = shark_clean_y["Sex"].str.strip().str.upper()

shark_clean_y["Sex"] = shark_clean_y["Sex"].fillna("Unknown")

shark_clean_y.loc[
    ~shark_clean_y["Sex"].isin(["M", "F"]),
    "Sex"
] = "Unknown"

In [25]:
# checking "Sex"

shark_clean_y["Sex"].value_counts(dropna=False)

Sex
M          3121
F           646
Unknown     231
Name: count, dtype: int64

In [26]:
# Cleaning "Age". Convert valid ages to numbers and replace unclear/non-numeric values with NaN

shark_clean_y["Age"] = pd.to_numeric(
    shark_clean_y["Age"],
    errors="coerce"
)

In [27]:
# checking "Age"

shark_clean_y["Age"].unique()

array([63., nan, 37., 24., 40., 43., 27., 71., 21., 69., 31., 13., 12.,
       17., 35., 19., 11., 20., 38., 39., 16., 22., 55., 26., 56., 25.,
       61., 14., 54., 48., 57.,  8.,  9.,  7., 85., 18., 66., 42., 45.,
       30., 60., 29., 58., 36., 23., 28., 68., 33., 15., 41., 49., 46.,
       65., 64., 32., 10., 62., 52., 44., 47., 59., 50., 34., 77., 73.,
       67.,  6., 53., 51., 75., 70.,  4., 74.,  3., 82., 72.,  5., 86.,
       84., 87.])

In [28]:
# Cleanign "Injury". Standardize Injury text for keyword-based categorization

shark_clean_y["Injury_clean"] = (
    shark_clean_y["Injury"]
    .str.strip()
    .str.lower()
)

In [29]:
# checking key-words to create new injury categories

keywords = [
    "fatal",
    "bite",
    "bitten",
    "wound",
    "puncture",
    "laceration",
    "lost",
    "amput",
    "minor",
    "scratch",
    "abrasion",
    "no injury",
    "uninjured",
    "survived"
]

for word in keywords:
    count = shark_clean_y["Injury_clean"].str.contains(
        word,
        case=False,
        na=False
    ).sum()
    
    print(word, count)

fatal 403
bite 128
bitten 1020
wound 209
puncture 240
laceration 777
lost 8
amput 36
minor 284
scratch 18
abrasion 30
no injury 541
uninjured 2
survived 52

In [30]:
# Categorize injury descriptions based on keywords

def categorize_injury(text):
    if pd.isna(text):
        return "Unknown"

    if any(word in text for word in [
        "no details", "not stated", "unknown", "none to report"
    ]):
        return "Unknown"

    if "fatal" in text:
        return "Fatal"

    elif "no injury" in text or "uninjured" in text:
        return "No injury"

    elif any(word in text for word in [
        "amput", "sever", "lost", "torn off",
        "stripped of flesh", "tissue loss"
    ]):
        return "Severe injury"

    elif any(word in text for word in [
        "minor", "scratch", "abrasion"
    ]):
        return "Minor injury"

    elif any(word in text for word in [
        "bite", "bitten", "wound", "puncture",
        "lacerat", "injur", "gash", "cut"
    ]):
        return "Injury"

    else:
        return "Other"

In [31]:
# making a new column "Injury_Category" (instead of old "Injury")

shark_clean_y["Injury_Category"] = shark_clean_y["Injury_clean"].apply(categorize_injury)

In [32]:
# Final injury categories

shark_clean_y["Injury_Category"].value_counts(dropna=False)

Injury_Category
Injury           2222
No injury         543
Fatal             402
Minor injury      316
Other             265
Severe injury     205
Unknown            45
Name: count, dtype: int64

In [33]:
# Keep only the final cleaned columns

shark_clean_y = shark_clean_y[
    ["Sex", "Age", "Injury_Category"]
].copy()

In [34]:
# checking the result of my cleaning

shark_clean_y.head(20)

   Sex   Age Injury_Category
0    M  63.0           Other
1    M   NaN          Injury
2    F  37.0          Injury
3    M   NaN   Severe injury
4    M  24.0           Other
5    M   NaN          Injury
6    M  40.0          Injury
7    F   NaN          Injury
8    F   NaN       No injury
9    M  43.0          Injury
10   M   NaN       No injury
11   M  27.0          Injury
12   M  71.0       No injury
13   M   NaN          Injury
14   M  21.0          Injury
15   M  69.0          Injury
16   M   NaN          Injury
17   M   NaN          Injury
18   M  31.0   Severe injury
19   M   NaN          Injury

# Cleaning data values for Fatal, Species and Time columns

## Fatal Y/N

In [35]:
# checking all entries for a column Fatal
shark_attack['Fatal Y/N'].value_counts()

Fatal Y/N
N          3258
Y           438
UNKNOWN      24
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
Name: count, dtype: int64

In [36]:
# cleaning values for Fatal Y/N to have only: Y, N, UNKNOWN
shark_attack['Fatal Y/N'] = shark_attack['Fatal Y/N'].replace(["F", "M", "Y x 2"], "Y")

In [37]:
shark_attack['Fatal Y/N'] = shark_attack['Fatal Y/N'].replace(["n", "Nq"], "N")

In [38]:
# cleaning values for Time, first checking how many unique values we have
shark_attack['Time'].nunique()

434

In [39]:
# Extract and replace digits using RegEx and converts to a string. \D+ for all strings that do not contain digits or characters

cleaned = shark_attack['Time'].astype(str).str.replace(r'\D+', '', regex=True)

In [40]:
# See the distribution of digit counts
print(cleaned.str.len().value_counts())

Time
4.0     2228
0.0      437
8.0       16
3.0        5
6.0        2
1.0        2
2.0        2
5.0        2
10.0       1
Name: count, dtype: int64

In [41]:
#removing values with 8 digits, after a first check, they could be replaced to first 4 digits
cleaned = cleaned.mask(cleaned.str.len() == 8, cleaned.str[:4])

In [42]:
#check again the distribution, the 3-10 digits due to low number can be ignored
print(cleaned.str.len().value_counts())

Time
4.0     2244
0.0      437
3.0        5
6.0        2
1.0        2
2.0        2
5.0        2
10.0       1
Name: count, dtype: int64

In [43]:
# Keeping only valid 4-digit strings, convert everything else to NaN, and format to HH:MM
shark_attack['Time'] = pd.to_datetime(
    cleaned.where(cleaned.str.len() == 4),
    format='%H%M',
    errors='coerce'
).dt.strftime('%H:%M')

In [44]:
# Checking the column entries
shark_attack['Time'].head(20)

0     10:15
1     10:30
2     17:30
3     09:45
4     16:40
5     11:00
6     16:35
7     13:40
8     13:30
9     17:00
10      NaN
11    16:15
12    13:00
13    17:15
14    17:30
15      NaN
16    17:00
17      NaN
18    09:00
19      NaN
Name: Time, dtype: str

## Species

In [45]:
shark_attack.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species '],
      dtype='str')

In [46]:
#fixing Species column name by removing the space
shark_attack.rename(columns = {'Species ': 'Species'}, inplace = True)

In [47]:
# checking most mentioned shark types
shark_attack['Species'].value_counts().head(30)

Species
White shark                                           137
Shark involvement not confirmed                        73
Bull shark                                             62
Tiger shark                                            62
Shark involvement prior to death was not confirmed     52
Invalid                                                42
4' shark                                               37
6' shark                                               28
4' to 5' shark                                         25
Blacktip shark                                         22
5' shark                                               22
Unknown                                                21
3' shark                                               21
2 m shark                                              21
No shark involvement                                   21
3' to 4' shark                                         20
Wobbegong shark                                        20
1.2 m [4'] shark                                       18
Not stated                                             17
Nurse shark                                            17
3 m shark                                              15
1.8 m [6'] shark                                       14
1.5 m [5'] shark                                       14
Raggedtooth shark                                      13
1.2 m to 1.5 m [4' to 5'] shark                        13
Lemon shark                                            12
Bronze whaler shark                                    12
1.5 m shark                                            12
6 m [20'] white shark                                  12
5 m [16.5'] white shark                                12
Name: count, dtype: int64

In [48]:
import numpy as np

# Define conditions for the most mentioned shark types
conditions = [
    shark_attack['Species'].str.contains('white', case=False, na=False),
    shark_attack['Species'].str.contains('tiger', case=False, na=False),
    shark_attack['Species'].str.contains('bull', case=False, na=False),
    shark_attack['Species'].str.contains('nurse', case=False, na=False),
    shark_attack['Species'].str.contains('blacktip', case=False, na=False),
    shark_attack['Species'].str.contains('wobbegong', case=False, na=False),
    shark_attack['Species'].str.contains('raggedtooth', case=False, na=False),
    shark_attack['Species'].str.contains('lemon', case=False, na=False),
    shark_attack['Species'].str.contains('bronze whaler', case=False, na=False),
]

# Define corresponding standard names
choices = [
    'White Shark',
    'Tiger Shark',
    'Bull Shark',
    'Nurse Shark',
    'Blacktip Shark',
    'Wobbegong Shark',
    'Raggedtooth Shark',
    'Lemon Shark',
    'Bronze Whaler Shark',
]

# Assign to an existing column (anything else becomes 'Other/Unknown'), with that we remove the null values as well
shark_attack['Species'] = np.select(conditions, choices, default='Other/Unknown')

# Cleaning Null Values for Fatal and Time columns

In [49]:
# Count the number of null values in both columns
shark_attack[["Fatal Y/N", "Time"]].isna().sum()

Fatal Y/N     266
Time         1754
dtype: int64

In [50]:
# renaming all Null values
shark_attack["Time"] = shark_attack["Time"].fillna("No time specified")

In [51]:
shark_attack["Fatal Y/N"] = shark_attack["Fatal Y/N"].fillna("UNKNOWN")

In [52]:
shark_attack["Fatal Y/N"].value_counts()

Fatal Y/N
N          3260
Y           447
UNKNOWN     290
2017          1
Name: count, dtype: int64

In [53]:
# for some reason there was "2017" that could not be located by using ==, therefore, it was be removed by using .contains()
shark_attack['Fatal Y/N'] = shark_attack['Fatal Y/N'].astype(str).str.strip().replace({'2017': 'UNKNOWN'})

In [54]:
#final check if we missed any null values
shark_attack[["Time","Species","Fatal Y/N"]].isnull().sum()

Time         0
Species      0
Fatal Y/N    0
dtype: int64

In [55]:
shark_clean_tfs = shark_attack[["Time", "Species", "Fatal Y/N"]]

In [56]:
shark_clean_tfs.head(10)

    Time        Species Fatal Y/N
0  10:15    White Shark         Y
1  10:30    White Shark         N
2  17:30  Other/Unknown         N
3  09:45  Other/Unknown         N
4  16:40    Tiger Shark         N
5  11:00  Other/Unknown         N
6  16:35     Bull Shark         N
7  13:40  Other/Unknown         N
8  13:30    Tiger Shark         N
9  17:00  Other/Unknown         N

In [57]:
# Add Date, Year and Type to the cleaned DataFrame
shark_clean[["Date", "Year", "Type"]] = shark_attack[["Date", "Year", "Type"]]

In [58]:
display(shark_clean[["Date", "Year", "Type"]].head(50))

               Date    Year          Type
0    18th September  2026.0    Unprovoked
1    16th September  2026.0    Unprovoked
2    14th September  2026.0    Unprovoked
3   13th September   2026.0    Unprovoked
4     7th September  2026.0    Unprovoked
5    2nd September   2026.0    Unprovoked
6     1st September  2026.0    Unprovoked
7       31st August  2026.0    Unprovoked
8       26th August  2026.0    Unprovoked
9      23rd August   2026.0    Unprovoked
10      19th August  2026.0      Provoked
11      11th August  2026.0      Provoked
12       8th August  2026.0    Unprovoked
13        29th July  2026.0    Unprovoked
14        25th July  2026.0    Unprovoked
15       24th July   2026.0    Unprovoked
16       24th July   2026.0    Unprovoked
17        21st July  2026.0    Unprovoked
18       18th July   2026.0    Unprovoked
19         3rd July  2026.0    Unprovoked
20         1st July  2026.0      Provoked
21        23rd June  2026.0    Unprovoked
22        13th June  2026.0    Unprovoked
23        13th June  2026.0    Unprovoked
24        11th June  2026.0    Unprovoked
25         8th June  2026.0    Unprovoked
26         6th June  2026.0    Unprovoked
27         5th June  2026.0      Provoked
28        1st June   2026.0    Unprovoked
29         1st June  2026.0    Unprovoked
30         31st May  2026.0    Unprovoked
31         30th May  2026.0    Unprovoked
32         25th May  2026.0      Provoked
33         24th May  2026.0    Unprovoked
34         22nd May  2026.0    Unprovoked
35         17th May  2026.0  Questionable
36         16th May  2026.0    Unprovoked
37       14th April  2026.0    UNprovoked
38        3rd April  2026.0    Unprovoked
39       26th March  2026.0    Unprovoked
40       25th March  2026.0    Unprovoked
41  22nd-23rd March  2026.0    Unprovoked
42       18th March  2026.0    Unprovoked
43       14th March  2026.0    Unprovoked
44       10th March  2026.0    Unprovoked
45        5th March  2026.0    Unprovoked
46    22nd February  2026.0    Unprovoked
47     6th February  2026.0    Unprovoked
48     29th January  2026.0    Unprovoked
49     29th January  2026.0    Unprovoked

In [59]:
#Convert "Year"" to integers
shark_clean["Year"] = pd.to_numeric(
    shark_clean["Year"],
    errors="coerce"
).astype("Int64")

In [60]:
#Check "Year"
shark_clean["Year"] = pd.to_numeric(shark_clean["Year"],errors="coerce").astype("Int64")

In [61]:
print(shark_clean["Year"].head())
print(shark_clean["Year"].dtype)
print("Missing years:", shark_clean["Year"].isna().sum())

0    2026
1    2026
2    2026
3    2026
4    2026
Name: Year, dtype: Int64
Int64
Missing years: 0

In [62]:
#Clean "Type"
shark_clean["Type"] = shark_clean["Type"].str.strip()
shark_clean["Type"] = shark_clean["Type"].replace("", pd.NA)
shark_clean["Type"] = shark_clean["Type"].str.title()

In [63]:
#Check the data types cleanned
print(shark_clean["Type"].value_counts(dropna=False))

Type
Unprovoked             3162
Provoked                304
Invalid                 266
Watercraft              176
Sea Disaster             45
Questionable             27
NaN                      14
?                         1
Unconfirmed               1
Unverified                1
Under Investigation       1
Name: count, dtype: int64

In [64]:
#Clean Date as text
shark_clean["Date"] = shark_clean["Date"].str.strip()
shark_clean["Date"] = shark_clean["Date"].replace("", pd.NA)

In [65]:
#Remove ordinal suffixes
shark_clean["Date"] = shark_clean["Date"].str.replace(r"(\d+)(st|nd|rd|th)",r"\1",regex=True)

In [66]:
print(shark_clean["Date"].head(20))

0     18 September
1     16 September
2     14 September
3     13 September
4      7 September
5      2 September
6      1 September
7        31 August
8        26 August
9        23 August
10       19 August
11       11 August
12        8 August
13         29 July
14         25 July
15         24 July
16         24 July
17         21 July
18         18 July
19          3 July
Name: Date, dtype: str

In [67]:
#Check date

print(shark_clean["Date"].sample(50).to_string())

1649    05-Oct-2011
1025    06-Aug-2016
3662      04/jan/85
72       14 October
3560         nov/87
472       27/mar/21
3133    28-Sep-1995
2378    28-May-2005
638     07-Sep-2019
1470    08-May-2013
3869       Apr-1980
760     18-Aug-2018
390     24-Dec-2021
3056    03-Feb-1997
699       16/mar/19
1672    23-Aug-2011
98          17 June
2132    28-Aug-2007
3354      08/mar/92
1301    28-Aug-2014
164       24/mai/24
220     22 Aug-2023
366       18/mar/22
1445      19/jul/13
830     03-Feb-2018
3546    14-Feb-1988
1141    09-Oct-2015
515     25-Oct-2020
442       27/jun/21
1317    01-Aug-2014
1098    19-Feb-2016
1119    19-Dec-2015
3100    07-May-1996
1090      26/mar/16
2285    09-Apr-2006
584       22/mar/20
3207    01-Dec-1994
3607       Sep-1986
2768    26-Feb-2001
2187      22/mar/07
992     30-Oct-2016
2572    26-Apr-2003
1715    13-May-2011
3735      15/jun/83
3877      13/jan/80
597       07/jan/20
84         1 August
174       02/mar/24
1121    11-Dec-2015
3529      05/jun/88

In [68]:
print("Missing dates:", shark_clean["Date"].isna().sum())

Missing dates: 0

In [69]:
#after check, we can see that some of the dates are not in a standard format. We will need to clean this column further to ensure consistency and accuracy in our analysis.
#we mainly need the date for month/season analysis, while Year can handle trends over time.
#Rather than heavily modifying Date, I'd preserve it and create a new Month column.

In [70]:
#Formating Date column
shark_clean["Date"] = shark_clean["Date"].str.lower()
shark_clean["Date"] = shark_clean["Date"].str.replace("out", "oct", regex=False)
print(shark_clean["Date"].sample(100).to_string())

3203    reported      10-dec-1994
1854                  20-dec-2009
17                        21 july
3628                    12/jan/86
1061                    04/jun/16
762                   15-aug-2018
3784                    10/mar/82
2499                    12/jan/04
2006                  30-aug-2008
3930                  19-feb-1978
3281                    30/jul/93
2517                    01/nov/03
690                   21-apr-2019
1593                  11-apr-2012
1550                    31/jul/12
2423                  30-oct-2004
3655                    03/mar/85
1574                    14/jun/12
2616                  29-sep-2002
3934                         1978
1966                    11/jan/09
3028                  11-aug-1997
3575                    13/jun/87
3353                    10/mar/92
1321                    21/jul/14
2536                  14-sep-2003
3279                     aug-1993
317                   15-aug-2022
2640                    20/jun/02
2551                    05/jul/03
308                   07-oct-2022
3223                    09/jul/94
2564                    08/jun/03
3909                  29-dec-1978
2886                       nov/99
726                     11/nov/18
3932                    06/jan/78
916                     18/jun/17
3810                  27-sep-1981
3895                    19/jun/79
1456                    25/jun/13
247                   28-may 2023
3318         reported 12-nov-1992
3732                    29/jun/83
761                   15-aug-2018
571                   30-may-2020
3910                  12-dec-1978
2354                  14-aug-2005
1126                    15/nov/15
2238                  20-aug-2006
1765                  30-oct-2010
370                     13/mar/22
668                     21/jun/19
412                   28-aug-2021
2356                   6-aug-2005
2870         reported 28-jan-2000
3387                    01/jul/91
3873                    11/mar/80
1732                    16/mar/11
76                   27 september
3288                    09/jun/93
3259                    12/nov/93
2599                  20-dec-2002
3066                    18/nov/96
888                   23-aug-2017
384                     09/jan/22
1682                  01-aug-2011
2977                    08/jun/98
1857                  18-dec-2009
1841                    27/jan/10
383                     22/jan/22
2345                  05-sep-2005
323                     27/jul/22
2284                  09-apr-2006
2548                    20/jul/03
1898         reported 24-jul-2009
3394                    07/jun/91
2202                    09/jan/07
1155                  19-sep-2015
3436                  08-apr-1990
1671                  24-aug-2011
3151                  15-aug-1995
3110                  09-feb-1996
1778                  24-sep-2010
3175                    16/jun/95
3405                    09/jan/91
1396                    07/nov/13
9                       23 august
3419                  08-sep-1990
3845                    01/jan/81
3975                  12-sep-1976
309                   06-oct-2022
2503                         2004
2234                  27-aug-2006
1315                  02-aug-2014
1861                  05-dec-2009
3990                    12/mar/76
355                   03-may-2022
3964                    26/nov/76
224                   12 aug-2023

In [71]:
#Create new column "Month" based on the "Date" column
shark_clean["Month"] = pd.NA

In [72]:
shark_clean[["Date", "Year", "Month"]].head(100)

            Date  Year Month
0   18 september  2026  <NA>
1   16 september  2026  <NA>
2   14 september  2026  <NA>
3   13 september  2026  <NA>
4    7 september  2026  <NA>
..           ...   ...   ...
95       29 june  2025  <NA>
96       25 june  2025  <NA>
97       22 june  2025  <NA>
98       17 june  2025  <NA>
99     11/jun/25  2025  <NA>

[100 rows x 3 columns]

In [73]:
shark_clean["Date"].str.contains("jan", case=False, na=False)

0       False
1       False
2       False
3       False
4       False
        ...
3995     True
3996     True
3997     True
3998     True
3999    False
Name: Date, Length: 3998, dtype: bool

In [74]:
shark_clean.loc[shark_clean["Date"].str.contains("jan", case=False, na=False),"Month"] = "January"
shark_clean.loc[shark_clean["Date"].str.contains("feb", case=False, na=False),"Month"] = "February"
shark_clean.loc[shark_clean["Date"].str.contains("mar", case=False, na=False),"Month"] = "March"
shark_clean.loc[shark_clean["Date"].str.contains("apr", case=False, na=False),"Month"] = "April"
shark_clean.loc[shark_clean["Date"].str.contains("may", case=False, na=False),"Month"] = "May"
shark_clean.loc[shark_clean["Date"].str.contains("jun", case=False, na=False),"Month"] = "June"
shark_clean.loc[shark_clean["Date"].str.contains("jul", case=False, na=False),"Month"] = "July"
shark_clean.loc[shark_clean["Date"].str.contains("aug", case=False, na=False),"Month"] = "August"
shark_clean.loc[shark_clean["Date"].str.contains("sep", case=False, na=False),"Month"] = "September"
shark_clean.loc[shark_clean["Date"].str.contains("oct", case=False, na=False),"Month"] = "October"
shark_clean.loc[shark_clean["Date"].str.contains("nov", case=False, na=False),"Month"] = "November"
shark_clean.loc[shark_clean["Date"].str.contains("dec", case=False, na=False),"Month"] = "December"

In [75]:
#check Month column cleanned
shark_clean["Month"].value_counts(dropna=False)

Month
July         498
September    396
August       396
June         364
October      338
April        298
May          296
January      293
March        283
November     263
December     253
February     228
<NA>          92
Name: count, dtype: int64

In [76]:
#Check the "NA" values in the "Month" column 
shark_clean.loc[shark_clean["Month"].isna(),["Date", "Year", "Month"]].head(50)

             Date  Year Month
101     29/mai/25  2025  <NA>
102     26/mai/25  2025  <NA>
103     15/mai/25  2025  <NA>
104     08/mai/25  2025  <NA>
105     21/abr/25  2025  <NA>
106     20/abr/25  2025  <NA>
107     19/abr/25  2025  <NA>
108     12/abr/25  2025  <NA>
113     27/fev/25  2025  <NA>
115     22/fev/25  2025  <NA>
116     22/fev/25  2025  <NA>
117     22/fev/25  2025  <NA>
118     10/fev/25  2025  <NA>
119     10/fev/25  2025  <NA>
120     07/fev/25  2025  <NA>
121     03/fev/25  2025  <NA>
128     30/dez/24  2024  <NA>
129     29/dez/24  2024  <NA>
130     29/dez/24  2024  <NA>
131     28/dez/24  2024  <NA>
132     02/dez/24  2024  <NA>
133     01/dez/24  2024  <NA>
142     26/set/24  2024  <NA>
143     17/set/24  2024  <NA>
144     16/set/24  2024  <NA>
145     26/ago/24  2024  <NA>
146     06/ago/24  2024  <NA>
163     28/mai/24  2024  <NA>
164     24/mai/24  2024  <NA>
165     23/mai/24  2024  <NA>
166     02/mai/24  2024  <NA>
167     26/abr/24  2024  <NA>
168     26/abr/24  2024  <NA>
169     20/abr/24  2024  <NA>
170     20/abr/24  2024  <NA>
171     08/abr/24  2024  <NA>
251     20/mai/23  2023  <NA>
919    2017.06.05  2017  <NA>
1381         2014  2014  <NA>
1382         2014  2014  <NA>
2085   2008.01.30  2008  <NA>
2091    fall 2008  2008  <NA>
2092  summer-2008  2008  <NA>
2205        2007.  2007  <NA>
2503         2004  2004  <NA>
2761   02-ap-2001  2001  <NA>
2872         2000  2000  <NA>
2937         1999  1999  <NA>
2938         1999  1999  <NA>
3001         1998  1998  <NA>

In [77]:
#Fixing the portuguese month names
shark_clean.loc[shark_clean["Date"].str.contains("fev", case=False, na=False),"Month"] = "February"
shark_clean.loc[shark_clean["Date"].str.contains("mar", case=False, na=False),"Month"] = "March"
shark_clean.loc[shark_clean["Date"].str.contains("abr", case=False, na=False),"Month"] = "April"
shark_clean.loc[shark_clean["Date"].str.contains("mai", case=False, na=False),"Month"] = "May"
shark_clean.loc[shark_clean["Date"].str.contains("jun", case=False, na=False),"Month"] = "June"
shark_clean.loc[shark_clean["Date"].str.contains("jul", case=False, na=False),"Month"] = "July"
shark_clean.loc[shark_clean["Date"].str.contains("ago", case=False, na=False),"Month"] = "August"
shark_clean.loc[shark_clean["Date"].str.contains("set", case=False, na=False),"Month"] = "September"
shark_clean.loc[shark_clean["Date"].str.contains("out", case=False, na=False),"Month"] = "October"
shark_clean.loc[shark_clean["Date"].str.contains("nov", case=False, na=False),"Month"] = "November"
shark_clean.loc[shark_clean["Date"].str.contains("dez", case=False, na=False),"Month"] = "December"

In [78]:
#Check the "Month" column after formating
shark_clean["Month"].value_counts(dropna=False)

Month
July         498
September    399
August       398
June         364
October      338
April        307
May          305
January      293
March        283
November     263
December     259
February     236
<NA>          55
Name: count, dtype: int64

In [79]:
#Checke the remaining "NA" values in the "Month" column
shark_clean.loc[shark_clean["Month"].isna(),["Date", "Year", "Month"]].head(60)

                                    Date  Year Month
919                           2017.06.05  2017  <NA>
1381                                2014  2014  <NA>
1382                                2014  2014  <NA>
2085                          2008.01.30  2008  <NA>
2091                           fall 2008  2008  <NA>
2092                         summer-2008  2008  <NA>
2205                               2007.  2007  <NA>
2503                                2004  2004  <NA>
2761                          02-ap-2001  2001  <NA>
2872                                2000  2000  <NA>
2937                                1999  1999  <NA>
2938                                1999  1999  <NA>
3001                                1998  1998  <NA>
3002                                1998  1998  <NA>
3003                                1998  1998  <NA>
3120                                1996  1996  <NA>
3121                                1996  1996  <NA>
3195                                1995  1995  <NA>
3196                                1995  1995  <NA>
3197                                1995  1995  <NA>
3198                                1995  1995  <NA>
3254  last incident of 1994 in hong kong  1994  <NA>
3255                                1994  1994  <NA>
3308                           fall 1993  1993  <NA>
3310                                1993  1993  <NA>
3311                                1993  1993  <NA>
3367                                1992  1992  <NA>
3445                                1990  1990  <NA>
3498                                1989  1989  <NA>
3499                                1989  1989  <NA>
3555                                1988  1988  <NA>
3589                                1987  1987  <NA>
3590                                1987  1987  <NA>
3629                                1986  1986  <NA>
3665                                1985  1985  <NA>
3666                                1985  1985  <NA>
3705                                1984  1984  <NA>
3706                                1984  1984  <NA>
3754                            ca. 1983  1983  <NA>
3755                                1983  1983  <NA>
3756                                1983  1983  <NA>
3796                                1982  1982  <NA>
3797                                1982  1982  <NA>
3798                                1982  1982  <NA>
3846                                1981  1981  <NA>
3847                      summer of 1981  1981  <NA>
3848                          12-30-1980  1980  <NA>
3880                         summer 1980  1980  <NA>
3881                               1980s  1980  <NA>
3882                                1980  1980  <NA>
3883                               1980s  1980  <NA>
3908                                1979  1979  <NA>
3933                                1978  1978  <NA>
3934                                1978  1978  <NA>
3999                                1976  1976  <NA>

In [80]:
#Formating the remaining  NA values in the "Date" column as possible
shark_clean.loc[919, "Month"] = "June"
shark_clean.loc[2085, "Month"] = "January"  
shark_clean.loc[2761, "Month"] = "April"  
shark_clean.loc[3848, "Month"] = "December"

In [81]:
shark_clean["Month"].value_counts(dropna=False)

Month
July         498
September    399
August       398
June         365
October      338
April        308
May          305
January      294
March        283
November     263
December     260
February     236
<NA>          51
Name: count, dtype: int64

In [82]:
shark_clean.loc[shark_clean["Month"].isna(),["Date", "Year", "Month"]]

                                    Date  Year Month
1381                                2014  2014  <NA>
1382                                2014  2014  <NA>
2091                           fall 2008  2008  <NA>
2092                         summer-2008  2008  <NA>
2205                               2007.  2007  <NA>
2503                                2004  2004  <NA>
2872                                2000  2000  <NA>
2937                                1999  1999  <NA>
2938                                1999  1999  <NA>
3001                                1998  1998  <NA>
3002                                1998  1998  <NA>
3003                                1998  1998  <NA>
3120                                1996  1996  <NA>
3121                                1996  1996  <NA>
3195                                1995  1995  <NA>
3196                                1995  1995  <NA>
3197                                1995  1995  <NA>
3198                                1995  1995  <NA>
3254  last incident of 1994 in hong kong  1994  <NA>
3255                                1994  1994  <NA>
3308                           fall 1993  1993  <NA>
3310                                1993  1993  <NA>
3311                                1993  1993  <NA>
3367                                1992  1992  <NA>
3445                                1990  1990  <NA>
3498                                1989  1989  <NA>
3499                                1989  1989  <NA>
3555                                1988  1988  <NA>
3589                                1987  1987  <NA>
3590                                1987  1987  <NA>
3629                                1986  1986  <NA>
3665                                1985  1985  <NA>
3666                                1985  1985  <NA>
3705                                1984  1984  <NA>
3706                                1984  1984  <NA>
3754                            ca. 1983  1983  <NA>
3755                                1983  1983  <NA>
3756                                1983  1983  <NA>
3796                                1982  1982  <NA>
3797                                1982  1982  <NA>
3798                                1982  1982  <NA>
3846                                1981  1981  <NA>
3847                      summer of 1981  1981  <NA>
3880                         summer 1980  1980  <NA>
3881                               1980s  1980  <NA>
3882                                1980  1980  <NA>
3883                               1980s  1980  <NA>
3908                                1979  1979  <NA>
3933                                1978  1978  <NA>
3934                                1978  1978  <NA>
3999                                1976  1976  <NA>

In [83]:
#See all existing Type categories
shark_clean["Type"].value_counts(dropna=False)

Type
Unprovoked             3162
Provoked                304
Invalid                 266
Watercraft              176
Sea Disaster             45
Questionable             27
NaN                      14
?                         1
Unconfirmed               1
Unverified                1
Under Investigation       1
Name: count, dtype: int64

In [84]:
#remove spaces around the values, standardize capitalization for type
shark_clean["Type"] = shark_clean["Type"].str.strip()
shark_clean["Type"] = shark_clean["Type"].str.title()

In [85]:
shark_clean["Type"].value_counts(dropna=False)

Type
Unprovoked             3162
Provoked                304
Invalid                 266
Watercraft              176
Sea Disaster             45
Questionable             27
NaN                      14
?                         1
Unconfirmed               1
Unverified                1
Under Investigation       1
Name: count, dtype: int64

In [86]:
shark_clean["Type"] = shark_clean["Type"].replace("?", pd.NA)

In [87]:
shark_clean["Type"].value_counts(dropna=False)

Type
Unprovoked             3162
Provoked                304
Invalid                 266
Watercraft              176
Sea Disaster             45
Questionable             27
NaN                      15
Unconfirmed               1
Unverified                1
Under Investigation       1
Name: count, dtype: int64

In [88]:
#Creating the final cleaned DataFrame with the selected columns "date", "year", "month", "type", 
cleaned_columns_2 = shark_clean[["Date", "Year", "Month", "Type"]].copy()

In [89]:
#Check
cleaned_columns_2.head()

           Date  Year      Month        Type
0  18 september  2026  September  Unprovoked
1  16 september  2026  September  Unprovoked
2  14 september  2026  September  Unprovoked
3  13 september  2026  September  Unprovoked
4   7 september  2026  September  Unprovoked

In [90]:
#check shape
cleaned_columns_2.shape

(3998, 4)

# Clean columns

In [91]:
shark_clean_tfs.head(10)

    Time        Species Fatal Y/N
0  10:15    White Shark         Y
1  10:30    White Shark         N
2  17:30  Other/Unknown         N
3  09:45  Other/Unknown         N
4  16:40    Tiger Shark         N
5  11:00  Other/Unknown         N
6  16:35     Bull Shark         N
7  13:40  Other/Unknown         N
8  13:30    Tiger Shark         N
9  17:00  Other/Unknown         N

In [92]:
shark_clean_y.head(10)

  Sex   Age Injury_Category
0   M  63.0           Other
1   M   NaN          Injury
2   F  37.0          Injury
3   M   NaN   Severe injury
4   M  24.0           Other
5   M   NaN          Injury
6   M  40.0          Injury
7   F   NaN          Injury
8   F   NaN       No injury
9   M  43.0          Injury

In [93]:
shark_clean.head(10)

,Country,State,Location,Activity,Date,Year,Type,Month
0,Australia,Western Australia,Sorrento Beach Perth,Swimming,18 september,2026,Unprovoked,September
1,Canada,Quebec,Off The Coast Of Perce Le Bilbo Dive Site,Diving,16 september,2026,Unprovoked,September
2,Bahamas,Bimini,Bimini Island,Swimming,14 september,2026,Unprovoked,September
3,Australia,Western Australia,Geraldton,Surfing,13 september,2026,Unprovoked,September
4,Usa,Hawaii,Honolulu,Surfing,7 september,2026,Unprovoked,September
5,Usa,Florida,New Smyrna Beach,Surfing,2 september,2026,Unprovoked,September
6,Usa,Florida,30 Miles Off Pensacola,Spearfishing,1 september,2026,Unprovoked,September
7,Usa,Massachusetts,Norton Point Edgartown Marthas Vinyard,Swimming,31 august,2026,Unprovoked,August
8,Usa,Hawaii,"Ala Moana Beach Park, Oahu",Surfing,26 august,2026,Unprovoked,August
9,Usa,Florida,Boca Grande (Island In The Keys),Wading on a sandbar,23 august,2026,Unprovoked,August

In [94]:
print(shark_clean_tfs.shape)
print(shark_clean_y.shape)
print(shark_clean.shape)
print(cleaned_columns_2.shape)

(3998, 3)
(3998, 3)
(3998, 8)
(3998, 4)

In [95]:
print(shark_clean_tfs.index.equals(shark_clean_y.index))
print(shark_clean_tfs.index.equals(shark_clean.index))
print(shark_clean_tfs.index.equals(cleaned_columns_2.index))

True
True
True

In [96]:
# Combine all cleaned columns into one final dataframe
shark_clean_final = pd.concat(
    [
        shark_clean,
        shark_clean_y,
        shark_clean_tfs
    ],
    axis=1
)

# Clean Final df

In [111]:
shark_clean_final.head(0)

Empty DataFrame
Columns: [Country, State, Location, Activity, Date, Year, Type, Month, Sex, Age, Injury_Category, Time, Species, Fatal Y/N]
Index: []

# H1 - Top 10 Destinations by Shark Incidents

In [113]:
#Analyzing Country data:
shark_clean_final["Country"].value_counts().head(10)

Country
Usa              1898
Australia         725
South Africa      349
Bahamas           117
Brazil            115
New Zealand        72
New Caledonia      59
Reunion            54
Mexico             50
Egypt              36
Name: count, dtype: int64

In [115]:
top_10_countries = shark_clean_final["Country"].value_counts().head(10)
top_10_countries

Country
Usa              1898
Australia         725
South Africa      349
Bahamas           117
Brazil            115
New Zealand        72
New Caledonia      59
Reunion            54
Mexico             50
Egypt              36
Name: count, dtype: int64

In [117]:
#Checktotal incidentes
total_incidents = len(shark_clean_final)
print(total_incidents)

3998

In [125]:
#Calculate Incident % per country

incident_percentage = ((top_10_countries / total_incidents) * 100).round(2)
incident_percentage

Country
Usa              47.47
Australia        18.13
South Africa      8.73
Bahamas           2.93
Brazil            2.88
New Zealand       1.80
New Caledonia     1.48
Reunion           1.35
Mexico            1.25
Egypt             0.90
Name: count, dtype: float64

In [ ]:
# Calculate Fatality % per country

In [ ]:
# Check Fatality data
shark_clean_final["Fatal Y/N"].value_counts(dropna=False)

Fatal Y/N
N          3260
Y           447
UNKNOWN     291
Name: count, dtype: int64

In [128]:
#Exclude 291 unknown cases
known_outcomes = shark_clean_final[shark_clean_final["Fatal Y/N"].isin(["Y", "N"])]
known_outcomes["Fatal Y/N"].value_counts()

Fatal Y/N
N    3260
Y     447
Name: count, dtype: int64

In [133]:
#Check for each country
fatal_by_country = known_outcomes[known_outcomes["Fatal Y/N"] == "Y"]["Country"].value_counts()
fatal_by_country.head(10)

Country
Australia        89
Usa              64
South Africa     43
Brazil           32
Reunion          24
New Caledonia    22
Mexico           15
Hong Kong        12
Egypt            11
Fiji             10
Name: count, dtype: int64

In [ ]:
#Incidents by country
known_by_country = known_outcomes["Country"].value_counts()
known_by_country.head(10)

Country
Usa              1787
Australia         666
South Africa      311
Bahamas           110
Brazil            105
New Zealand        67
New Caledonia      58
Reunion            54
Mexico             45
Egypt              34
Name: count, dtype: int64

In [136]:
#Calculate calculate Fatality % per country
fatal_by_country
known_by_country
fatality_percentage = ((fatal_by_country / known_by_country) * 100).round(2)
fatality_percentage.head(10)

Country
Angola                           NaN
Aruba                         100.00
Atlantic Ocean                   NaN
Australia                      13.36
Azores                           NaN
Bahamas                         6.36
Belize                           NaN
Bermuda                          NaN
Brazil                         30.48
British Overseas Territory       NaN
Name: count, dtype: float64

In [139]:
#Fatality percentage aligned with the Top 10 countries list
fatal_top10 = fatal_by_country.reindex(top_10_countries.index,fill_value=0)
fatal_top10

Country
Usa              64
Australia        89
South Africa     43
Bahamas           7
Brazil           32
New Zealand       7
New Caledonia    22
Reunion          24
Mexico           15
Egypt            11
Name: count, dtype: int64

In [142]:
#align known_by_country with the Top 10 countries list
known_by_country
known_top10 = known_by_country.reindex(top_10_countries.index,fill_value=0)
known_top10

Country
Usa              1787
Australia         666
South Africa      311
Bahamas           110
Brazil            105
New Zealand        67
New Caledonia      58
Reunion            54
Mexico             45
Egypt              34
Name: count, dtype: int64

In [143]:
#Calculate fatality_top10
fatality_top10 = ((fatal_top10 / known_top10) * 100).round(2)
fatality_top10

Country
Usa               3.58
Australia        13.36
South Africa     13.83
Bahamas           6.36
Brazil           30.48
New Zealand      10.45
New Caledonia    37.93
Reunion          44.44
Mexico           33.33
Egypt            32.35
Name: count, dtype: float64

In [146]:
#Create final data frame for Destination Analysis

country_analysis = pd.DataFrame({"Incidents": top_10_countries,"Incident %": incident_percentage, "Fatal Incidents": fatal_top10, "Fatality %": fatality_top10})

# Display the result
country_analysis

               Incidents  Incident %  Fatal Incidents  Fatality %
Country
Usa                 1898       47.47               64        3.58
Australia            725       18.13               89       13.36
South Africa         349        8.73               43       13.83
Bahamas              117        2.93                7        6.36
Brazil               115        2.88               32       30.48
New Zealand           72        1.80                7       10.45
New Caledonia         59        1.48               22       37.93
Reunion               54        1.35               24       44.44
Mexico                50        1.25               15       33.33
Egypt                 36        0.90               11       32.35